import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SortingAlgorithmProvider } from "@/context/Visualizer";

// Menginisialisasi font Inter dengan subset Latin
const inter = Inter({ subsets: ["latin"] });

// Metadata untuk aplikasi, termasuk judul dan deskripsi
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Komponen RootLayout merupakan layout utama aplikasi
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Menambahkan kelas CSS untuk font Inter */}
      <body className={inter.className}>
        {/* Membungkus konten anak dengan SortingAlgorithmProvider untuk menyediakan konteks algoritma pengurutan */}
        <SortingAlgorithmProvider>{children}</SortingAlgorithmProvider>
      </body>
    </html>
  );
}
